sudo: required

language: java
jdk:
  - oraclejdk8

services:
 - docker

before_install:
 - mkdir -p output

script:
 - cd blueprint-parent && mvn -B -V clean install
 - cp -R target/generated-docs/*/html/* ../output

after_success:
 - cd output ; rm -R .asciidoctor
 - git init
 - git config user.name "${GH_USER_NAME}"
 - git config user.email "{GH_USER_EMAIL}"
 - git add . ; git commit -m "Deploy to GitHub Pages - ${TRAVIS_COMMIT_RANGE}"
 - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1

