== Monitoring

=== Overview

This chapters gives an about the monitoring mechanism in this application using Codahale Metrics and Spring Actuator.

=== Spring Actuator

With the Spring actuator extension gather the application a lot of information like

* Configuration information (http://localhost:8099/autoconfig)
* Available beans (http://localhost:8099/beans)
* Perform a Thread dump (http://localhost:8099/dump)
* Health information with disk space (http://localhost:8099/health)
* Metrics. If Codahale Metrics is in classpath than contains this endpoints also this information (http://localhost:8099/metrics)
* Trace information, the last 100 request (http://localhost:8099/trace)

Some of the information are very sensitive, this is reason why the security is in general active and disallows the access without credentials. To deactivate - for dev purposes ;-) - use this parameter in `application.properties` `management.security.enabled=false`.

A detailed list of the availabe endpoints and configuratoin possibilities are described here:
https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html

To activate this module is only a dependency necessary
[source,xml]
----
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
----

=== Coda Hale Metrics

http://metrics.dropwizard.io[Coda Hale metrics] is one of the most famous metrics implementation. For providing own metrics is it advisable to use this lib for gather and deliver different kinds of metric information.

Spring automatically determine the existins of Coda Hale Metrics in the classpaths and replace some of the own implementations with the one from Coda Hale/Dropwizard. The metrics will be also exposed via the /metrics endpoint.

To integrate Coda Hale/Dropwizard metrics add this dependency to the pom.xml
[source,xml]
----
<dependency>
	<groupId>io.dropwizard.metrics</groupId>
	<artifactId>metrics-core</artifactId>
	<version>${dropwizard.metrics.version}</version>
</dependency>
----

For an usage look at the `com.haddouti.pg.blueprint.note.infra.monitoring.NoteEventMonitoring<T>` implementation and the result at the metrics endpoint; see in the next listing a result with the own metrics

* com.haddouti.pg.blueprint.note.infra.monitoring.NoteEventMonitoring.responses.*: A timer metric holding different values for the response time
* com.haddouti.pg.blueprint.note.infra.monitoring.NoteEventMonitoring.executed-events: Representing a counter metrics representing the number of events

[source,json]
----
{
	"mem": 508751,
	"mem.free": 216697,
	"processors": 2,
	"instance.uptime": 93563,
	"uptime": 105687,
	"systemload.average": 1.37,
	"heap.committed": 437248,
	"heap.init": 129024,
	"heap.used": 220550,
	"heap": 1815040,
	"nonheap.committed": 73488,
	"nonheap.init": 2496,
	"nonheap.used": 71503,
	"nonheap": 0,
	"threads.peak": 21,
	"threads.daemon": 19,
	"threads.totalStarted": 26,
	"threads": 21,
	"classes": 10317,
	"classes.loaded": 10317,
	"classes.unloaded": 0,
	"gc.ps_scavenge.count": 10,
	"gc.ps_scavenge.time": 195,
	"gc.ps_marksweep.count": 2,
	"gc.ps_marksweep.time": 189,
	"com.haddouti.pg.blueprint.note.infra.monitoring.NoteEventMonitoring.responses.snapshot.mean": 1,
	"gauge.response.metrics": 16.0,
	"com.haddouti.pg.blueprint.note.infra.monitoring.NoteEventMonitoring.executed-events": 4,
	"gauge.response.note.v1.note": 18.0,
	"counter.status.200.note.v1.note": 4,
	"com.haddouti.pg.blueprint.note.infra.monitoring.NoteEventMonitoring.responses.snapshot.75thPercentile": 2,
	"com.haddouti.pg.blueprint.note.infra.monitoring.NoteEventMonitoring.responses.snapshot.95thPercentile": 3,
	"gauge.response.star-star.favicon.ico": 4.0,
	"com.haddouti.pg.blueprint.note.infra.monitoring.NoteEventMonitoring.responses.snapshot.999thPercentile": 3,
	"com.haddouti.pg.blueprint.note.infra.monitoring.NoteEventMonitoring.responses.snapshot.98thPercentile": 3,
	"com.haddouti.pg.blueprint.note.infra.monitoring.NoteEventMonitoring.responses.snapshot.min": 0,
	"com.haddouti.pg.blueprint.note.infra.monitoring.NoteEventMonitoring.responses.snapshot.max": 3,
	"counter.status.200.star-star.favicon.ico": 4,
	"counter.status.200.metrics": 4,
	"com.haddouti.pg.blueprint.note.infra.monitoring.NoteEventMonitoring.responses.meanRate": 0.04149518995882756,
	"com.haddouti.pg.blueprint.note.infra.monitoring.NoteEventMonitoring.responses.snapshot.median": 2,
	"com.haddouti.pg.blueprint.note.infra.monitoring.NoteEventMonitoring.responses.snapshot.stdDev": 0,
	"com.haddouti.pg.blueprint.note.infra.monitoring.NoteEventMonitoring.responses.fifteenMinuteRate": 0.0044076009778713995,
	"com.haddouti.pg.blueprint.note.infra.monitoring.NoteEventMonitoring.responses.fiveMinuteRate": 0.013005185767779516,
	"com.haddouti.pg.blueprint.note.infra.monitoring.NoteEventMonitoring.responses.count": 4,
	"com.haddouti.pg.blueprint.note.infra.monitoring.NoteEventMonitoring.responses.snapshot.99thPercentile": 3,
	"com.haddouti.pg.blueprint.note.infra.monitoring.NoteEventMonitoring.responses.oneMinuteRate": 0.05895238133346083,
	"httpsessions.max": -1,
	"httpsessions.active": 0
}

----


=== References

* https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html

