= Blueprint
Hafid Haddouti <code@haddouti.com>
{project-version}

:toc:

== Summary
This project illustrate a compilation of different concepts and technical solution for "modern".footnote:[Tbd tomorrow] technology stack.


The key requirements for this blueprint are:

* onion architecture
** SOLID, especially focus on D=Dependency inversion principle
* reactivate
* well documented
* maintainable





== Architecture

The application is a web application with different endpoints.

=== Components

[plantuml, diagram-arch-components-general, png]
....
@startuml
!pragma graphviz_dot jdot
skinparam componentStyle uml2
interface "Metrics" as IMetrics
interface "Actuator" as IActuator
interface "REST" as IRest

IMetrics - [Blueprint App]
IActuator - [Blueprint App]
IRest - [Blueprint App]

IMetrics - [Monitoring]
@enduml
....

==== Blueprint App

The Blueprint application 

[plantuml, diagram-arch-components-blueprint-app, png]
....
@startuml
!pragma graphviz_dot jdot
skinparam componentStyle uml2

package "Blueprint App" {
	[Blueprint Web] --> [Blueprint Ejb]
}

@enduml
....

